import type { NextPage } from 'next'
import Head from 'next/head'
import Script from 'next/script'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <script src='./sc.js'></script> */}
      </Head>
      {/* <Script src='/sc.js' strategy='lazyOnload'></Script> */}
      <nav className={styles.mainnav}>
        <ul>
          <li>Home</li>
          <li>About</li>
          <li>Blogs</li>
          <li>Contact</li>
        </ul>
      </nav>
      <main className={styles.main}>
        <h1 className={styles.title}>
         Blog App In Next.js!
        </h1>

        <p className={styles.description}>
          Get started by every{' '}
          <code className={styles.code}>programmer</code>
        </p>
        <div className="blogs">
          <h2>Popular blogs</h2>
          <div className="blog-items">
            <h3>How to learn JS in 2021</h3>
            <p>JS is used for desgining web logic</p>
          </div>
          <div className="blog-items">
            <h3>How to learn JS in 2021</h3>
            <p>JS is used for desgining web logic</p>
          </div>
          <div className="blog-items">
            <h3>How to learn JS in 2021</h3>
            <p>JS is used for desgining web logic</p>
          </div>
        </div>
      </main>
    </div>
  )
}

export default Home
